// src/componenet/chatStyles.js
export const styles = {
  pageContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100vw",
    height: "100vh",
    backgroundColor: "#efeae2",
    margin: 0,
    padding: 0,
    overflow: "hidden",
    fontFamily: "sans-serif",
  },
  chatContainer: {
    width: "100%",
    maxWidth: "800px",
    height: "100vh",
    backgroundColor: "#efeae2",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 4px 12px rgba(0,0,0,0.15)",
    borderLeft: "1px solid #ccc",
    borderRight: "1px solid #ccc",
  },
  header: {
    backgroundColor: "#005c4b",
    color: "#ffffff",
    padding: "12px 16px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    boxShadow: "0 2px 5px rgba(0,0,0,0.1)",
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  avatar: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    backgroundColor: "#ccc",
    color: "#005c4b",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
    fontSize: "18px",
  },
  roomTitle: {
    margin: 0,
    fontSize: "16px",
    fontWeight: "600",
  },
  onlineStatus: {
    fontSize: "12px",
    color: "#a8fabd",
  },
  leaveBtn: {
    backgroundColor: "#ea0038",
    color: "white",
    border: "none",
    padding: "6px 12px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "600",
  },
  messagesArea: {
    flex: 1,
    padding: "16px",
    overflowY: "auto",
    backgroundColor: "#efeae2",
    backgroundImage: "radial-gradient(#d1d7db 0.75px, transparent 0.75px)",
    backgroundSize: "15px 15px",
  },
  messageBubble: {
    maxWidth: "70%",
    padding: "8px 12px",
    borderRadius: "8px",
    fontSize: "14px",
    boxShadow: "0 1px 0.5px rgba(0,0,0,0.1)",
    wordBreak: "break-word",
    position: "relative",
  },
  myMessage: {
    backgroundColor: "#d9fdd3",
    color: "#111",
    borderTopRightRadius: "0",
    marginLeft: "auto",
  },
  otherMessage: {
    backgroundColor: "#ffffff",
    color: "#111",
    borderTopLeftRadius: "0",
    marginRight: "auto",
  },
  senderName: {
    fontSize: "11px",
    fontWeight: "bold",
    color: "#00a884",
    marginBottom: "2px",
  },
  timeText: {
    fontSize: "9px",
    color: "#666",
    textAlign: "right",
    marginTop: "2px",
  },
  inputForm: {
    backgroundColor: "#f0f2f5",
    padding: "12px 16px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    borderTop: "1px solid #ddd",
  },
  inputBox: {
    flex: 1,
    padding: "12px 18px",
    borderRadius: "20px",
    border: "1px solid #ccc",
    outline: "none",
    fontSize: "14px",
    backgroundColor: "#fff",
    color: "#000000",
  },
  sendBtn: {
    backgroundColor: "#00a884",
    color: "white",
    border: "none",
    padding: "10px 20px",
    borderRadius: "20px",
    cursor: "pointer",
    fontWeight: "600",
  },
};